// app/layout.tsx
import { ClerkProvider } from "@clerk/nextjs";
import { dark, shadesOfPurple } from "@clerk/themes";

// import { Inter } from 'next/font/google';
import { Poppins } from "next/font/google";
import "./globals.css";
import { NotificationProvider } from "@/components/Pages/NotificationProvider";
import ContactDialog from "@/components/Pages/ContactDialog";

// const inter = Inter({ subsets: ['latin'] });

// 1. Load the font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300"],
  variable: "--font-poppins",
  display: "swap",
});
export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider

    // appearance={{
    //   baseTheme: [shadesOfPurple],
    //   variables: { colorPrimary: "" },
    //   signIn: {
    //     baseTheme: [shadesOfPurple],
    //     variables: { colorPrimary: "" },
    //   },
    // }}
    >
      <NotificationProvider>
        <html lang="en" className={poppins.className}>
          <body>{children}
             <ContactDialog />
          </body>
        </html>
      </NotificationProvider>
    </ClerkProvider>
  );
}
